spring:
  application:
    name: eurekaserver
  security:
    basic:
      enable: true
    user:
      name: eureka-user
      password: 1234567890

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
